import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ChevronRight, CircleCheck, Compass, Heart, LockKeyhole, MapPin, PiggyBank, ShieldCheck, Sparkles, Users, Wrench } from "lucide-react";
import { Button } from "@/components/ui/Button";

const title = "Vanlife solo : le guide complet pour voyager seul en van";
const description = "Sécurité, choix du van, budget, communauté et itinéraires : préparez votre premier voyage en van solo en France avec des conseils concrets.";

export const metadata: Metadata = {
  title,
  description,
  alternates: { canonical: "/vanlife-solo" },
  keywords: ["vanlife solo", "voyager seul en van", "vanlife solo femme", "road trip solo France", "van pour une personne"],
  openGraph: { title, description, type: "article", url: "/vanlife-solo", images: [{ url: "/images/hero-label-vanlife.png", width: 1536, height: 1024, alt: "Voyage en van solo en France" }] },
};

const advice = [
  { icon: LockKeyhole, title: "Sécuriser son van", items: ["Renforcer les ouvrants avec du matériel adapté au véhicule", "Préserver l’intimité sans masquer la visibilité nécessaire à la conduite", "Stationner dans un lieu autorisé dont l’environnement vous inspire confiance", "Partager régulièrement son itinéraire avec un proche", "Garder téléphone, clés et lampe accessibles la nuit"] },
  { icon: MapPin, title: "Bien choisir ses étapes", items: ["Privilégier les accueils identifiés pour les premières nuits", "Lire des avis récents et croiser plusieurs sources", "Éviter de commencer par une zone isolée sans réseau", "Vérifier l’accès, le gabarit et les horaires avant d’arriver", "Changer d’endroit si une situation ne paraît pas rassurante"] },
  { icon: Users, title: "Créer du lien", items: ["Rejoindre des communautés de vanlifers actives et modérées", "Participer à un rassemblement ou une sortie collective", "Choisir ponctuellement des campings ou lieux avec espaces communs", "Demander des conseils locaux aux hôtes", "Conserver des rendez-vous réguliers avec ses proches"] },
  { icon: Wrench, title: "Gagner en autonomie", items: ["Savoir vérifier pneus, huile, liquide de refroidissement et batterie", "Apprendre à changer une roue si le véhicule le permet", "Conserver triangle, gilet, trousse de secours et matériel de dépannage", "Vérifier les garanties et limites de son assistance", "Tenir à jour les documents et numéros utiles"] },
  { icon: PiggyBank, title: "Construire son budget solo", items: ["Séparer carburant, nuits, alimentation, assurance et entretien", "Prévoir une réserve pour les réparations imprévues", "Adapter la distance parcourue au budget disponible", "Comparer le coût réel des différentes solutions de nuit", "Utiliser les avantages membres lorsque les conditions conviennent"] },
  { icon: Heart, title: "Prendre soin de soi", items: ["Installer des rituels simples pour structurer les journées", "Alterner temps seul et moments de sociabilité", "Tenir un carnet de voyage ou appeler régulièrement un proche", "Accepter les journées moins faciles sans culpabiliser", "Faire une pause en ville ou chez un proche si nécessaire"] },
] as const;

const vans = [
  { emoji: "🚗", title: "Ludospace compact", examples: "Citroën Berlingo, Peugeot Partner…", plus: "Discret, économique et facile à garer ; adapté aux escapades légères.", minus: "Volume et hauteur réduits : testez réellement le couchage avant l’achat.", fit: "Week-ends et voyage minimaliste" },
  { emoji: "🚐", title: "Fourgon intermédiaire", examples: "Renault Trafic, Opel Vivaro, Ford Transit Custom…", plus: "Bon compromis entre conduite quotidienne, couchage et rangement.", minus: "La hauteur intérieure et le plan d’aménagement demandent des choix précis.", fit: "Polyvalence et voyages réguliers" },
  { emoji: "🚌", title: "Transporter aménagé", examples: "Volkswagen Transporter et formats comparables", plus: "Format routier, réseau d’équipements et communauté de propriétaires importante.", minus: "Le prix d’achat et certaines pièces peuvent être élevés selon la génération.", fit: "Confort compact et usage mixte" },
  { emoji: "🚚", title: "Grand fourgon", examples: "Renault Master, Fiat Ducato, Sprinter…", plus: "Lit fixe, davantage de réserves et possibilité de tenir debout.", minus: "Plus coûteux à équiper, à assurer et à déplacer dans les centres-villes.", fit: "Long voyage ou télétravail" },
] as const;

const itineraries = [
  { emoji: "🌊", title: "Bretagne en solo", duration: "10 à 14 jours", stages: "Saint-Malo · Cap Fréhel · Crozon · Pointe du Raz · Morbihan", text: "Des paysages puissants, de nombreux villages et des étapes variées pour alterner solitude choisie et rencontres." },
  { emoji: "🌻", title: "Provence et Verdon", duration: "7 à 10 jours", stages: "Verdon · Moustiers · Luberon · Alpilles · Camargue", text: "Un parcours culturel et naturel particulièrement agréable hors de la très haute saison." },
  { emoji: "🏔️", title: "Traversée des Pyrénées", duration: "14 à 21 jours", stages: "Pays basque · Gavarnie · Ariège · Foix", text: "Un voyage plus engagé où météo, réseau mobile et niveau des randonnées doivent être vérifiés étape par étape." },
] as const;

const faqs = [
  { question: "La vanlife solo est-elle dangereuse ?", answer: "Aucun voyage n’est sans risque. Une préparation sérieuse réduit l’exposition aux vols, pannes, accidents et situations d’isolement : véhicule entretenu, étapes autorisées, contacts réguliers, conduite reposée et capacité à changer de lieu si nécessaire." },
  { question: "Quel budget prévoir en solo ?", answer: "Le budget dépend fortement du véhicule, des kilomètres, de la saison et du nombre de nuits payantes. Établissez vos propres enveloppes pour le carburant, l’alimentation, les étapes, l’assurance et l’entretien, puis ajoutez une réserve pour les imprévus." },
  { question: "Comment rencontrer d’autres vanlifers ?", answer: "Les lieux d’accueil, campings, événements et communautés en ligne facilitent les rencontres. Privilégiez les groupes actifs et modérés, et organisez toujours une première rencontre dans un lieu public ou identifié." },
  { question: "Peut-on commencer sans expérience ?", answer: "Oui. Commencez par une nuit proche de chez vous, puis un week-end et enfin une semaine. Cette progression permet de tester le couchage, l’énergie, l’eau, le rangement et votre propre rapport à la solitude." },
] as const;

export default function VanlifeSoloPage() {
  const schemas = [
    { "@context": "https://schema.org", "@type": "Article", headline: title, description, image: "https://labelvanlife.com/images/hero-label-vanlife.png", author: { "@type": "Organization", name: "Label Vanlife" }, publisher: { "@type": "Organization", name: "Label Vanlife" }, mainEntityOfPage: "https://labelvanlife.com/vanlife-solo" },
    { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) },
  ];

  return (
    <main className="bg-white pb-24 pt-16 text-neutral-800">
      {schemas.map((schema, index) => <script key={index} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />)}
      <div className="mx-auto max-w-6xl px-6 pt-8"><nav aria-label="Fil d’Ariane" className="flex flex-wrap items-center gap-2 text-xs text-neutral-400"><Link href="/" className="hover:text-emerald-700">Accueil</Link><ChevronRight className="h-3.5 w-3.5" /><Link href="/vanlife" className="hover:text-emerald-700">Vanlife France</Link><ChevronRight className="h-3.5 w-3.5" /><span className="text-neutral-700">Vanlife solo</span></nav></div>

      <header className="mx-auto grid max-w-6xl gap-10 px-6 py-12 lg:grid-cols-[.95fr_1.05fr] lg:items-center lg:py-16"><div className="animate-fade-in-up"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#9a7445]">Guide vanlife</p><h1 className="mt-4 text-4xl font-bold leading-[1.08] text-neutral-950 sm:text-6xl">Vanlife solo : voyager seul, libre et bien préparé</h1><p className="mt-5 text-lg leading-8 text-neutral-600">Partir quand on veut, modifier l’itinéraire et s’arrêter là où cela nous plaît : la liberté est immense. Pour qu’elle reste agréable, elle se prépare.</p><div className="mt-7 flex flex-wrap gap-2">{["Sécurité", "Choix du van", "Budget solo", "Itinéraires", "Communauté"].map((tag) => <span key={tag} className="rounded-full border border-[#c39960]/30 bg-[#f7f1e8] px-3 py-1.5 text-xs font-semibold text-[#7d5d38]">{tag}</span>)}</div></div><div className="relative aspect-[4/3] overflow-hidden rounded-[2rem] shadow-2xl shadow-neutral-900/15"><Image src="/images/hero-label-vanlife.png" alt="Voyage en van solo au bord d’un lac" fill priority sizes="(max-width: 1024px) 100vw, 52vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black/35 to-transparent" /></div></header>

      <article className="mx-auto max-w-5xl space-y-20 px-6">
        <section className="mx-auto max-w-3xl text-lg leading-8 text-neutral-600"><p>La vanlife solo convient aussi bien à une première escapade qu’à un long voyage. Elle offre un rythme personnel et une grande capacité d’improvisation, mais demande de prendre seul les décisions liées à la route, au stationnement et aux imprévus.</p><blockquote className="mt-8 rounded-r-2xl border-l-4 border-[#c39960] bg-[#f7f1e8] px-7 py-6 text-xl font-semibold leading-8 text-neutral-900">« L’objectif n’est pas de tout prévoir : c’est d’avoir assez de repères pour rester libre quand le programme change. »</blockquote></section>

        <section><div className="text-center"><Compass className="mx-auto h-9 w-9 text-emerald-700" /><p className="mt-3 text-xs font-bold uppercase tracking-[0.2em] text-[#9a7445]">Les fondamentaux</p><h2 className="mt-3 text-3xl font-bold text-neutral-950 sm:text-4xl">6 conseils essentiels pour la vanlife solo</h2></div><div className="mt-10 grid gap-5 md:grid-cols-2">{advice.map(({ icon: Icon, title: adviceTitle, items }, index) => <section key={adviceTitle} className="micro-card relative overflow-hidden rounded-2xl border border-neutral-200 bg-white p-6"><span className="absolute right-5 top-3 text-5xl font-black text-neutral-100">{String(index + 1).padStart(2, "0")}</span><span className="micro-icon relative flex h-11 w-11 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><Icon className="h-5 w-5" /></span><h3 className="relative mt-5 text-xl font-bold text-neutral-950">{adviceTitle}</h3><ul className="relative mt-4 space-y-3">{items.map((item) => <li key={item} className="flex gap-2 text-sm leading-6 text-neutral-600"><CircleCheck className="mt-1 h-4 w-4 shrink-0 text-emerald-600" />{item}</li>)}</ul></section>)}</div></section>

        <section className="rounded-3xl bg-neutral-950 p-7 text-white sm:p-10"><div className="grid gap-8 lg:grid-cols-[.75fr_1.25fr] lg:items-start"><div><ShieldCheck className="h-9 w-9 text-[#c39960]" /><p className="mt-4 text-xs font-bold uppercase tracking-[0.2em] text-[#d6b98f]">Des étapes plus lisibles</p><h2 className="mt-3 text-3xl font-bold">Pourquoi choisir un lieu labellisé en solo ?</h2><p className="mt-4 leading-7 text-white/60">Une fiche détaillée et un établissement identifié permettent de préparer l’arrivée et de réduire l’incertitude, particulièrement lors des premières nuits.</p><Link href="/devenir-membre" className="mt-6 inline-flex"><Button variant="cta">Obtenir ma carte membre <ArrowRight className="h-4 w-4" /></Button></Link><p className="mt-3 text-xs text-white/40">29 € cette année au lieu de 39 €.</p></div><ul className="grid gap-3 sm:grid-cols-2">{["Établissement et accueil identifiés", "Informations utiles avant l’arrivée", "Avantages de 10 à 20 % selon le lieu", "Carte interactive réservée aux membres"].map((item) => <li key={item} className="flex gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 text-sm text-white/75"><CircleCheck className="h-5 w-5 shrink-0 text-emerald-400" />{item}</li>)}</ul></div></section>

        <section><div className="text-center"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#9a7445]">Le véhicule adapté à votre usage</p><h2 className="mt-3 text-3xl font-bold text-neutral-950 sm:text-4xl">Quel van choisir pour voyager seul ?</h2><p className="mx-auto mt-4 max-w-2xl text-neutral-600">Commencez par votre usage, votre gabarit et votre budget total. Les modèles ne sont que des exemples : l’état réel, l’historique et l’aménagement comptent davantage que le logo.</p></div><div className="mt-10 grid gap-5 sm:grid-cols-2">{vans.map((van) => <article key={van.title} className="micro-card rounded-2xl border border-neutral-200 p-6"><span className="text-3xl" aria-hidden="true">{van.emoji}</span><h3 className="mt-4 text-xl font-bold text-neutral-950">{van.title}</h3><p className="mt-1 text-xs font-semibold text-[#9a7445]">{van.examples}</p><p className="mt-4 text-sm leading-6 text-neutral-600"><strong className="text-emerald-700">Atout :</strong> {van.plus}</p><p className="mt-2 text-sm leading-6 text-neutral-600"><strong className="text-rose-700">À vérifier :</strong> {van.minus}</p><p className="mt-4 rounded-xl bg-neutral-50 px-4 py-3 text-xs font-bold text-neutral-700">Idéal pour : {van.fit}</p></article>)}</div></section>

        <section><div className="text-center"><Sparkles className="mx-auto h-9 w-9 text-emerald-700" /><p className="mt-3 text-xs font-bold uppercase tracking-[0.2em] text-[#9a7445]">Premiers voyages</p><h2 className="mt-3 text-3xl font-bold text-neutral-950 sm:text-4xl">3 itinéraires adaptés à la vanlife solo</h2></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{itineraries.map((trip) => <article key={trip.title} className="micro-card rounded-2xl border border-neutral-200 p-6"><span className="text-3xl" aria-hidden="true">{trip.emoji}</span><h3 className="mt-4 text-xl font-bold text-neutral-950">{trip.title}</h3><span className="mt-2 inline-flex rounded-full bg-[#f7f1e8] px-3 py-1 text-xs font-bold text-[#7d5d38]">{trip.duration}</span><p className="mt-4 text-sm font-semibold leading-6 text-emerald-800">{trip.stages}</p><p className="mt-3 text-sm leading-6 text-neutral-600">{trip.text}</p><Link href="/road-trips" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-neutral-900 hover:text-emerald-700">Préparer l’itinéraire <ArrowRight className="h-4 w-4" /></Link></article>)}</div></section>

        <section><div className="text-center"><h2 className="text-3xl font-bold text-neutral-950 sm:text-4xl">Questions fréquentes</h2></div><div className="mt-8 divide-y divide-neutral-200 overflow-hidden rounded-2xl border border-neutral-200">{faqs.map((faq) => <details key={faq.question} className="group p-5 open:bg-[#f7f1e8]/50 sm:p-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 font-bold text-neutral-900"><span>{faq.question}</span><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-neutral-100 text-lg transition group-open:rotate-45 group-open:bg-[#c39960] group-open:text-white">+</span></summary><p className="mt-4 pr-10 text-sm leading-7 text-neutral-600">{faq.answer}</p></details>)}</div></section>

        <section className="rounded-3xl bg-gradient-to-br from-emerald-600 to-emerald-800 p-8 text-center text-white sm:p-12"><p className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-200">Votre première étape</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Repérez un lieu où vous serez attendu</h2><p className="mx-auto mt-4 max-w-2xl text-emerald-50/80">Consultez les fiches des établissements labellisés et préparez votre arrivée avant de prendre la route.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/explorer"><Button variant="cta" size="lg" className="w-full sm:w-auto">Explorer les lieux <ArrowRight className="h-4 w-4" /></Button></Link><Link href="/dormir-en-van"><Button variant="secondary" size="lg" className="w-full sm:w-auto">Où dormir en van</Button></Link></div></section>
      </article>
    </main>
  );
}
