import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { serializeJsonLd } from "@/lib/seo/json-ld";
import { VehicleFitSimulator } from "@/components/VehicleFitSimulator";

const title = "Guide d’achat van et fourgon : choisir pour vos voyages";
const description = "Le guide d’achat Label Vanlife : comparer les véhicules, comprendre les options, préparer son budget et vérifier une occasion ou un projet d’aménagement.";
const illustration = "/images/mag/itineraires/guide-achat.webp";
export const metadata: Metadata = {
  title: "Guide d’achat van et fourgon", description, alternates: { canonical: "/guide-achat" },
  openGraph: { title, description, type: "article", url: "/guide-achat", images: [{ url: illustration, width: 1536, height: 1024, alt: "Comparer un van compact, un fourgon et un Combi avant l’achat" }] },
  twitter: { card: "summary_large_image", title, description, images: [illustration] },
};

const formats = [
  { name: "Van compact", usage: "Des escapades et un véhicule que l’on envisage aussi au quotidien.", compromise: "Le volume demande de l’organisation : faire le lit peut transformer tout l’espace de vie.", check: "Testez les sièges enfants, le lit déplié et les rangements avec vos sacs. Mesurez la hauteur réelle, accessoires compris : le mot compact ne garantit pas l’accès aux parkings." },
  { name: "Fourgon aménagé", usage: "Des séjours où l’on souhaite davantage vivre à l’intérieur.", compromise: "Plus de volume peut aussi signifier un gabarit moins pratique dans certains villages.", check: "Essayez de circuler quand quelqu’un cuisine ou dort. Mesurez le couchage et vérifiez charge disponible, ventilation, chauffage et accès aux équipements pour l’entretien." },
  { name: "Combi ou van rétro", usage: "Le plaisir d’un véhicule de caractère et d’un voyage à son rythme.", compromise: "L’esthétique ne renseigne pas sur la corrosion, la mécanique ni la qualité d’une restauration.", check: "Faites examiner le véhicule par un spécialiste indépendant. Demandez factures, photos des travaux, disponibilité des pièces et conditions d’assistance adaptées à vos destinations." },
  { name: "Camping-car", usage: "Un espace de vie structuré pour un séjour prolongé, selon l’implantation.", compromise: "Longueur, largeur et hauteur demandent d’anticiper les accès et le stationnement.", check: "Comparez places route et couchages, charge disponible et stockage. Faites vérifier l’étanchéité et essayez toutes les fonctions de la cellule avant de vous décider." },
  { name: "Voiture et tente de toit", usage: "Voyager en gardant son véhicule, avec une installation de couchage séparée.", compromise: "Monter au lit, se changer et vivre sous la pluie restent des questions concrètes.", check: "Faites confirmer la compatibilité toit, barres et tente par leurs fabricants. Testez l’échelle et le repli. Demandez aux lieux d’accueil les emplacements et conditions adaptés." },
  { name: "Caravane", usage: "Installer une base au camping et explorer sans déplacer son hébergement.", compromise: "L’attelage, les manœuvres et le stockage nécessitent de la préparation.", check: "Faites confirmer la compatibilité du véhicule tracteur, les masses et le permis requis pour votre ensemble précis. Essayez une manœuvre avant de choisir un grand modèle." },
] as const;

const budget = [
  ["Le véhicule", "Prix TTC, version exacte, millésime, kilométrage et état ; précisez les frais de livraison ou de préparation."],
  ["Les options", "Séparez ce qui est de série, les packs imposés, les options choisies et les accessoires posés après livraison."],
  ["La mise à votre usage", "Couchages, transport des passagers, rangements, ventilation et équipements réellement nécessaires à vos voyages."],
  ["La remise en état", "Sur une occasion, chiffrez les travaux avec un professionnel avant de négocier : mécanique, pneus, corrosion et équipements de vie."],
  ["L’année de voyage", "Assurance, entretien, stockage, carburant, péages, traversées et nuits dans les lieux d’accueil."],
  ["La marge de sécurité", "Gardez une réserve adaptée à l’âge du véhicule et à votre projet, plutôt que d’absorber tout votre budget dans l’achat."],
] as const;

const checks = [
  "Le véhicule et le vendeur correspondent aux documents présentés ; j’ai vérifié le numéro d’identification.",
  "J’ai demandé le rapport HistoVec, les factures d’entretien et les documents applicables à la vente.",
  "J’ai lu le contrôle technique lorsqu’il est requis, sans le considérer comme une expertise complète du véhicule.",
  "Les places prévues pour voyager et les couchages correspondent à mon groupe : ce ne sont pas les mêmes informations.",
  "J’ai mesuré le lit, essayé sa mise en place et testé la circulation intérieure avec mes affaires.",
  "J’ai fait évaluer corrosion, infiltrations et mécanique ; je connais les travaux à prévoir et leur chiffrage.",
  "Le vendeur m’a montré les équipements en fonctionnement ; une installation douteuse sera contrôlée par un professionnel.",
  "J’ai demandé la masse réelle équipée et vérifié la marge pour les voyageurs, l’eau et les bagages.",
  "L’aménagement, les documents et l’usage déclaré à l’assureur sont cohérents ; les points de conformité ont été clarifiés.",
  "Le devis décrit précisément ce qui est inclus, les délais, les garanties applicables et les interlocuteurs après livraison.",
  "J’ai réalisé un essai adapté et, si possible, testé ce format en location avant de m’engager.",
  "Aucune question importante n’est restée sans réponse écrite avant mon engagement.",
] as const;

export default function BuyingGuidePage() {
  return <main className="bg-cream pb-20 pt-28 text-charcoal">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd({ "@context": "https://schema.org", "@type": "Article", headline: title, description, mainEntityOfPage: "https://www.labelvanlife.fr/guide-achat", image: `https://www.labelvanlife.fr${illustration}`, author: { "@type": "Organization", name: "Label Vanlife" } }) }} />
    <header className="mx-auto grid max-w-6xl items-center gap-10 px-6 py-12 lg:grid-cols-2">
      <div><p className="text-xs font-bold uppercase tracking-[0.2em]">Le guide d’achat Label Vanlife</p>
        <h1 className="mt-5 font-serif text-4xl leading-tight sm:text-6xl">Le bon véhicule.<br />Pour votre vraie vie.</h1>
        <p className="mt-6 text-xl leading-relaxed">Avant de choisir une marque, imaginez vos voyages : qui part, quand, combien de temps et avec quel confort ?</p>
        <p className="mt-4 leading-relaxed">Combi rétro, van, fourgon, tente de toit, caravane ou camping-car : aucun format ne fait de vous un meilleur voyageur. Le bon choix laisse de la place au respect, aux rencontres et au plaisir de partir.</p>
        <a href="#simulateur" className="mt-7 inline-flex min-h-11 items-center rounded-full bg-[#294c3b] px-6 py-3 font-semibold text-white">Trouver mon format de véhicule ↓</a>
      </div>
      <figure><Image src={illustration} alt="Illustration de deux acheteurs comparant un van bleu, un fourgon clair et un Combi jaune devant un atelier, avec une liste de points à vérifier" width={1536} height={1024} priority sizes="(max-width: 1024px) 100vw, 50vw" className="h-auto w-full rounded-3xl" /><figcaption className="mt-3 text-xs">Illustration éditoriale Label Vanlife, pas un essai comparatif de véhicules.</figcaption></figure>
    </header>
    <nav aria-label="Sommaire du guide d’achat" className="border-y border-charcoal/15"><div className="mx-auto flex max-w-6xl flex-wrap gap-x-6 gap-y-3 px-6 py-5 text-sm font-semibold">{[["simulateur", "Le simulateur"], ["besoins", "Votre usage"], ["formats", "Les formats"], ["budget", "Le vrai budget"], ["amenageur", "L’aménageur"], ["checklist", "Avant d’acheter"]].map(([id, label]) => <a key={id} href={`#${id}`} className="underline underline-offset-4">{label}</a>)}</div></nav>
    <article className="mx-auto max-w-6xl space-y-16 px-6 py-12">
      <VehicleFitSimulator />
      <section id="besoins" className="scroll-mt-28 max-w-3xl"><h2 className="font-serif text-3xl">01. Décrivez un week-end ordinaire</h2>
        <p className="mt-4 leading-relaxed">Pas seulement la belle photo au bord de l’eau : imaginez l’arrivée tardive, une journée de pluie et le départ du matin. Qui dort pendant que l’autre prépare le café ? Où sèchent les vêtements ? Où vont les chaussures et les affaires du chien ? Ces réponses dessinent une implantation plus utile qu’une longue liste d’options.</p>
        <ul className="mt-5 list-disc space-y-3 pl-5 leading-relaxed"><li><strong>L’équipage :</strong> comptez séparément les personnes transportées et celles qui dorment à bord, sans oublier les besoins d’accessibilité.</li><li><strong>Le rythme :</strong> week-ends, vacances longues ou usage quotidien ; été seulement ou saisons plus fraîches.</li><li><strong>Les nuits :</strong> si vous choisissez des campings équipés, certains besoins peuvent être couverts sur place. Vérifiez les services et horaires, ils ne sont pas identiques partout.</li><li><strong>Vos trois priorités :</strong> par exemple un vrai couchage, transporter les vélos et conserver un gabarit facile à conduire. Classez le reste en souhaits, pas en obligations.</li></ul>
      </section>
      <section id="formats" className="scroll-mt-28"><h2 className="font-serif text-3xl">02. Six formats, des compromis différents</h2><p className="mt-3 max-w-3xl leading-relaxed">Ces repères servent à préparer un essai, pas à désigner un gagnant. Deux véhicules du même format peuvent avoir des implantations et capacités très différentes.</p><div className="mt-7 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{formats.map(format => <section key={format.name} className="rounded-2xl border border-charcoal/15 bg-white p-6"><h3 className="font-serif text-2xl">{format.name}</h3><p className="mt-4 leading-relaxed">{format.usage}</p><p className="mt-4 text-sm leading-relaxed"><strong>Le compromis.</strong> {format.compromise}</p><p className="mt-4 text-sm leading-relaxed"><strong>À essayer.</strong> {format.check}</p></section>)}</div></section>
      <section id="budget" className="scroll-mt-28"><h2 className="font-serif text-3xl">03. Comparez le prix prêt à voyager</h2><p className="mt-4 max-w-3xl leading-relaxed">Un prix d’appel ne décrit pas toujours le véhicule que vous emporterez. Demandez deux devis avec la même liste d’équipements et le même périmètre. Une remise sur un ensemble suréquipé n’est pas forcément une économie pour votre usage.</p><dl className="mt-6 grid gap-4 md:grid-cols-2">{budget.map(([label, text]) => <div key={label} className="rounded-2xl border border-charcoal/15 bg-white p-5"><dt className="font-semibold">{label}</dt><dd className="mt-2 leading-relaxed">{text}</dd></div>)}</dl>
        <aside className="mt-6 rounded-2xl bg-[#294c3b] p-6 text-white"><h3 className="font-serif text-2xl">Le test des options</h3><p className="mt-3 leading-relaxed">Pour chaque équipement, demandez : « Quel problème résout-il pour moi, combien coûte-t-il installé, quel poids ajoute-t-il et comment sera-t-il entretenu ? » Comparez notamment occultation, couchage, table, moustiquaires et équipements de douche. Une décoration ou une finition n’a pas la même fonction qu’un équipement nécessaire à votre séjour.</p><p className="mt-3 text-sm leading-relaxed">Les tarifs et configurations évoluent : demandez un devis daté correspondant au véhicule réellement disponible. Ce guide ne présente aucun modèle comme testé ou labellisé par Label Vanlife.</p></aside>
      </section>
      <section className="max-w-3xl"><h2 className="font-serif text-3xl">04. Neuf, occasion ou aménagement ?</h2><div className="mt-5 space-y-4 leading-relaxed"><p><strong>Neuf :</strong> faites préciser la configuration livrée, les délais, les conditions de paiement et le service après-vente. Regardez le véhicule ou une implantation comparable, pas uniquement une photographie commerciale.</p><p><strong>Occasion :</strong> l’état documenté compte autant que l’âge et le kilométrage. Un contrôle technique ne remplace pas une expertise mécanique et une vérification de l’aménagement. Faites chiffrer les défauts avant de considérer le prix comme une bonne affaire.</p><p><strong>Projet sur mesure :</strong> validez d’abord l’usage, le porteur et la faisabilité. Ne commandez pas les équipements avant d’avoir clarifié les masses, la conformité et la prise en charge par l’assureur avec les interlocuteurs compétents.</p></div></section>
      <section id="amenageur" className="scroll-mt-28 rounded-3xl border border-charcoal/15 bg-white p-6 sm:p-8"><h2 className="font-serif text-3xl">05. Les bonnes questions à l’aménageur</h2><p className="mt-4 max-w-3xl leading-relaxed">Un bon échange commence par votre cahier des charges. Demandez à voir des réalisations comparables et des équipements accessibles pour la maintenance, plutôt qu’un décor seulement séduisant.</p><ul className="mt-5 list-disc space-y-3 pl-5 leading-relaxed"><li>Qui réalise les travaux et qui répond après la livraison ?</li><li>Quelles références d’équipements, prestations et exclusions figurent au devis ?</li><li>Quel calendrier, quels jalons et quelles modalités en cas de modification ?</li><li>Qui prend en charge les démarches de conformité nécessaires et quels documents seront remis ?</li><li>Comment les masses, la ventilation et les installations seront-elles contrôlées ?</li><li>Quels plans, notices, garanties applicables et consignes d’entretien recevrez-vous ?</li></ul><p className="mt-5 text-sm leading-relaxed">Une adresse dans un annuaire n’est pas une certification. Vérifiez directement les compétences, les références et les engagements du professionnel avant de lui confier votre projet.</p></section>
      <section id="checklist" className="scroll-mt-28"><h2 className="font-serif text-3xl">06. Votre checklist avant de vous engager</h2><p className="mt-3 leading-relaxed">Cochez au fil de la visite. Ces cases ne sont ni envoyées ni sauvegardées par Label Vanlife.</p><fieldset className="mt-6 space-y-3"><legend className="sr-only">Vérifications avant achat</legend>{checks.map((check, index) => <label key={check} className="flex cursor-pointer items-start gap-4 rounded-xl border border-charcoal/15 bg-white p-4"><input type="checkbox" name={`achat-${index}`} className="mt-1 h-5 w-5 shrink-0 accent-[#294c3b]" /><span className="leading-relaxed">{check}</span></label>)}</fieldset><p className="mt-5 text-sm leading-relaxed">Ce guide aide à préparer votre décision, il ne constitue ni une expertise du véhicule ni une validation de conformité. Faites intervenir un professionnel indépendant en cas de doute.</p></section>
      <section aria-labelledby="sources-achat" className="max-w-3xl border-t border-charcoal/20 pt-8"><h2 id="sources-achat" className="font-serif text-2xl">Les vérifications officielles</h2><p className="mt-3 text-sm">Liens consultés le 23 septembre 2026. Les démarches dépendent du véhicule et du projet.</p><ul className="mt-5 list-disc space-y-4 pl-5 leading-relaxed"><li>Demandez au vendeur de partager l’historique disponible : <a href="https://histovec.interieur.gouv.fr/histovec/acheteur" target="_blank" rel="noopener noreferrer" className="font-semibold underline">HistoVec — espace acheteur</a>.</li><li>Vérifiez les règles applicables au contrôle technique lors d’une vente : <a href="https://www.service-public.gouv.fr/particuliers/vosdroits/F16540" target="_blank" rel="noopener noreferrer" className="font-semibold underline">Service Public</a>.</li><li>Pour un véhicule transformé, clarifiez les démarches auprès du service régional compétent : <a href="https://www.ecologie.gouv.fr/politiques-publiques/homologation-vehicules" target="_blank" rel="noopener noreferrer" className="font-semibold underline">Ministère — homologation des véhicules</a>.</li></ul></section>
      <aside className="rounded-3xl bg-[#294c3b] p-8 text-white"><h2 className="font-serif text-3xl">Choisir moins de contraintes, garder plus de voyage.</h2><p className="mt-4 max-w-3xl leading-relaxed">Le véhicule est un moyen. Préparer des étapes où l’on sera accueilli, consommer local et préserver les lieux traversés donne du sens au départ.</p><Link href="/blog#itineraires" className="mt-6 inline-flex min-h-11 items-center rounded-full bg-cream px-6 py-3 font-semibold text-charcoal">Imaginer mon premier itinéraire →</Link></aside>
    </article>
  </main>;
}
