export type LabellisationCriterion = {
  id: string;
  category: "Accueil chaleureux" | "Respect de l'environnement" | "Qualité & confort" | "Sécurité & tranquillité" | "Esprit communautaire";
  emoji: string;
  title: string;
  description: string;
  examples: string[];
};

export const LABELLISATION_CRITERIA: LabellisationCriterion[] = [
  { id: "welcomeGift", category: "Accueil chaleureux", emoji: "☕", title: "Pot ou produit de bienvenue", description: "Un petit geste à l'arrivée : café, jus de fruit, fruits du jardin, confiture maison, carte de bienvenue personnalisée…", examples: ["Café/thé offert à l'arrivée", "Panier de produits locaux", "Carte manuscrite avec les bons plans", "Bouteille d'eau fraîche", "Pot de bienvenue tous les dimanches", "Pot de bienvenue tous les vendredis", "Pot de bienvenue hebdomadaire"] },
  { id: "usefulInfo", category: "Accueil chaleureux", emoji: "🗺️", title: "Informations utiles communiquées", description: "Les vanlifers ont accès à des informations claires : accès wifi, horaires d'eau chaude, règles du lieu, bons plans locaux.", examples: ["QR code avec infos pratiques", "Panneau d'affichage", "Livret d'accueil", "Message WhatsApp à l'arrivée"] },
  { id: "flexibleArrival", category: "Accueil chaleureux", emoji: "🕐", title: "Flexibilité sur les horaires d'arrivée", description: "Une arrivée tardive ou un départ tôt le matin est possible sans pénalité pour s'adapter à la vie en van.", examples: ["Arrivée possible après 20h", "Départ avant 8h accepté", "Code d'accès pour autonomie"] },
  { id: "pets", category: "Accueil chaleureux", emoji: "🐕", title: "Animaux de compagnie acceptés", description: "Les chiens et animaux de compagnie sont bienvenus, les vanlifers voyagent souvent avec leurs animaux.", examples: ["Chiens acceptés en laisse", "Point d'eau pour animaux", "Zone dédiée"] },

  { id: "waterSaving", category: "Respect de l'environnement", emoji: "💧", title: "Économiseurs d'eau installés", description: "Des dispositifs permettent de réduire la consommation d'eau : économiseurs sur robinets et douches, minuteries, récupération d'eau de pluie.", examples: ["Réducteurs de débit sur robinets", "Minuteries sur les douches", "Récupération eau de pluie", "Affichage de sensibilisation"] },
  { id: "wasteSorting", category: "Respect de l'environnement", emoji: "♻️", title: "Tri sélectif et compostage", description: "Des bacs de tri clairement identifiés sont à disposition, et idéalement un composteur pour les déchets organiques.", examples: ["Bacs de tri séparé (verre, plastique, carton)", "Composteur collectif", "Zone de dépôt des eaux grises"] },
  { id: "cleanEnergy", category: "Respect de l'environnement", emoji: "☀️", title: "Énergie propre ou économies d'énergie", description: "Des panneaux solaires, éclairage LED ou détecteurs de présence contribuent à réduire l'empreinte carbone du lieu.", examples: ["Panneaux solaires", "Éclairage LED", "Détecteurs de présence", "Chauffe-eau solaire"] },
  { id: "shortSupply", category: "Respect de l'environnement", emoji: "🌱", title: "Valorisation du local et circuit court", description: "Le lieu favorise les producteurs et artisans locaux, et encourage les vanlifers à consommer local.", examples: ["Vente de produits de la ferme", "Recommandation de producteurs locaux", "Marché ou AMAP à proximité signalé"] },

  { id: "sanitary", category: "Qualité & confort", emoji: "🚿", title: "Sanitaires propres et entretenus", description: "Les douches, WC et lavabos sont nettoyés quotidiennement et en bon état. L'eau chaude est disponible.", examples: ["Nettoyage quotidien", "Eau chaude garantie", "Produits d'entretien écologiques", "Musique d'ambiance", "Huiles essentielles"] },
  { id: "servicePoint", category: "Qualité & confort", emoji: "🔧", title: "Point de vidange eaux grises / noires", description: "Un point de vidange est disponible pour les eaux grises (évier) et idéalement les eaux noires (WC chimique).", examples: ["Borne de vidange eaux grises", "Point de remplissage eau potable"] },
  { id: "electricity", category: "Qualité & confort", emoji: "⚡", title: "Accès électricité ou recharge", description: "Des bornes ou prises électriques permettent aux vanlifers de recharger leurs équipements et batteries.", examples: ["Prise européenne (type E)", "Prise domestique (type F — comme à la maison)", "Électricité 6A", "Électricité 10A", "Électricité 16A ou plus", "Borne de recharge véhicule électrique", "Prise partagée disponible"] },
  { id: "internet", category: "Qualité & confort", emoji: "📶", title: "Connexion internet (wifi ou 4G/5G)", description: "Un accès wifi ou une bonne couverture réseau permet aux vanlifers nomades de travailler à distance.", examples: ["Wifi disponible gratuit", "Wifi payant", "Zone wifi gratuit", "Zone de coworking", "📵 Lieu déconnecté — sans réseau", "Bonne réception tous opérateurs", "4G/5G disponible", "Réception variable selon opérateur", "Mauvaise réception générale"] },
  { id: "food", category: "Qualité & confort", emoji: "🍽️", title: "Restauration sur place ou à proximité", description: "Une offre de restauration est disponible au camping ou dans les environs immédiats.", examples: ["Restaurant sur place", "Snack / bar sur place", "Pizzas / plats à emporter", "Épicerie sur place", "Restaurant à moins de 500m", "Restaurant à moins de 2km", "Food truck régulier", "Petit-déjeuner proposé", "Produits locaux en vente"] },
  { id: "wellbeing", category: "Qualité & confort", emoji: "🧘", title: "Animations & espace zen", description: "Des activités ou espaces de détente favorisent la reconnexion avec soi-même et la nature.", examples: ["Yoga", "Méditation", "Qi Gong", "Stretching", "Séance de respiration", "Espace zen / détente", "Hammock lounge", "Bain de forêt", "Sound healing"] },
  { id: "pool", category: "Qualité & confort", emoji: "🏊", title: "Piscine & espace bien-être", description: "Un accès piscine, spa ou bain nordique est proposé aux vanlifers pour se détendre.", examples: ["Piscine extérieure", "Piscine couverte", "Spa / jacuzzi", "Bain nordique", "Sauna", "Hammam", "Douche froide plongeon", "Accès lac / rivière"] },
  { id: "evening", category: "Qualité & confort", emoji: "🎶", title: "Ambiance & animations soirée", description: "Des animations en soirée rendent le séjour mémorable et créent du lien entre les vanlifers.", examples: ["Concert live", "Spectacle", "Soirée musicale", "DJ / ambiance musicale", "Karaoké", "Soirée thématique", "Cinéma en plein air", "Veillée contée", "Feu de camp animé"] },

  { id: "quiet", category: "Sécurité & tranquillité", emoji: "🌙", title: "Heures de silence respectées", description: "Des plages de calme sont définies et respectées (généralement 22h–7h), pour garantir le repos de tous.", examples: ["Silence après 22h", "Affichage des règles de bruit", "Pas de groupe bruyant près des vans"] },
  { id: "nightLighting", category: "Sécurité & tranquillité", emoji: "💡", title: "Éclairage nocturne suffisant", description: "Les chemins, sanitaires et zones communes sont éclairés la nuit pour se déplacer en sécurité.", examples: ["Lampadaires solaires", "Balisage des chemins", "Éclairage sanitaires 24h/24"] },
  { id: "rules", category: "Sécurité & tranquillité", emoji: "📋", title: "Règlement du lieu transmis aux vanlifers", description: "Les règles et consignes sont communiquées à l'arrivée, de manière claire et bienveillante.", examples: ["Règlement affiché à l'entrée", "Email de bienvenue avec règles", "Livret d'accueil"] },

  { id: "sharedSpace", category: "Esprit communautaire", emoji: "🔥", title: "Espace de convivialité partagé", description: "Un coin commun (feu de camp, barbecue, salon extérieur) favorise les rencontres entre vanlifers.", examples: ["Feu de camp autorisé", "Barbecue commun", "Table de pique-nique", "Terrasse partagée"] },
  { id: "vanliferManager", category: "Esprit communautaire", emoji: "🚐", title: "Propriétaire / gérant vanlifer", description: "Vous voyagez vous-même en van ou camping-car — vous comprenez les besoins des vanlifers de l'intérieur.", examples: ["Fourgon aménagé", "Camping-car", "Van de série aménagé", "Combi VW", "Van utilitaire aménagé maison", "✓ Dernier road trip"] },
  { id: "feedback", category: "Esprit communautaire", emoji: "🚀", title: "Ouverture aux retours et amélioration", description: "Les avis des vanlifers sont les bienvenus et pris en compte pour améliorer l'expérience.", examples: ["Cahier de suggestions", "Invitation à laisser un avis", "Suivi des retours clients"] },
];
