import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, CalendarDays, ChevronRight, MapPin, Route, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { ENRICHED_LIEUX } from "@/data/enriched-lieux";
import { getRegionGuide, REGION_GUIDES } from "@/data/region-guides";

type PageProps = { params: Promise<{ slug: string }> };

export function generateStaticParams() { return REGION_GUIDES.map(({ slug }) => ({ slug })); }

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const guide = getRegionGuide(slug);
  if (!guide) return {};
  const description = guide.intro;
  return { title: guide.title, description, alternates: { canonical: `/vanlife-regions/${slug}` }, keywords: [`vanlife ${guide.name}`, `road trip van ${guide.name}`, `itinéraire van ${guide.name}`], openGraph: { title: guide.title, description, type: "article", url: `/vanlife-regions/${slug}`, images: [{ url: "/images/hero-label-vanlife.png", width: 1536, height: 1024 }] } };
}

export default async function RegionGuidePage({ params }: PageProps) {
  const { slug } = await params;
  const guide = getRegionGuide(slug);
  if (!guide) notFound();
  const partners = guide.partnerIds.map((id) => ENRICHED_LIEUX.find((lieu) => lieu.id === id)).filter((lieu): lieu is NonNullable<typeof lieu> => Boolean(lieu));
  const schema = { "@context": "https://schema.org", "@type": "Article", headline: guide.title, description: guide.intro, image: "https://labelvanlife.com/images/hero-label-vanlife.png", author: { "@type": "Organization", name: "Label Vanlife" }, publisher: { "@type": "Organization", name: "Label Vanlife" }, mainEntityOfPage: `https://labelvanlife.com/vanlife-regions/${slug}` };

  return <main className="bg-white pb-24 pt-16 text-neutral-800"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><div className="mx-auto max-w-6xl px-6 pt-8"><nav aria-label="Fil d’Ariane" className="flex flex-wrap items-center gap-2 text-xs text-neutral-400"><Link href="/">Accueil</Link><ChevronRight className="h-3.5 w-3.5" /><Link href="/vanlife">Vanlife France</Link><ChevronRight className="h-3.5 w-3.5" /><Link href="/vanlife-regions">Destinations</Link><ChevronRight className="h-3.5 w-3.5" /><span className="text-neutral-700">{guide.name}</span></nav></div><header className="mx-auto grid max-w-6xl gap-10 px-6 py-12 lg:grid-cols-[.95fr_1.05fr] lg:items-center lg:py-16"><div className="animate-fade-in-up"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#9a7445]">{guide.eyebrow}</p><h1 className="mt-4 text-4xl font-bold leading-[1.08] text-neutral-950 sm:text-6xl">{guide.title}</h1><p className="mt-5 text-lg leading-8 text-neutral-600">{guide.intro}</p><div className="mt-7 flex flex-wrap gap-2">{guide.tags.map((tag) => <span key={tag} className="rounded-full border border-[#c39960]/30 bg-[#f7f1e8] px-3 py-1.5 text-xs font-semibold text-[#7d5d38]">{tag}</span>)}</div></div><div className="relative aspect-[4/3] overflow-hidden rounded-[2rem] shadow-2xl shadow-neutral-900/15"><Image src={partners[0]?.photoUrl || "/images/hero-label-vanlife.png"} alt={`Voyage en van en ${guide.name}`} fill priority sizes="(max-width:1024px) 100vw,52vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black/25 to-transparent" /></div></header>

  <article className="mx-auto max-w-5xl space-y-20 px-6"><section className="mx-auto max-w-3xl text-lg leading-8 text-neutral-600"><h2 className="text-3xl font-bold text-neutral-950">{guide.whyTitle}</h2>{guide.paragraphs.map((paragraph) => <p key={paragraph} className="mt-5">{paragraph}</p>)}</section><section className="grid gap-4 rounded-3xl bg-neutral-950 p-6 text-white sm:grid-cols-2 sm:p-8 lg:grid-cols-4"><div><CalendarDays className="h-6 w-6 text-[#c39960]" /><p className="mt-3 text-xs uppercase tracking-widest text-white/40">Meilleure période</p><p className="mt-1 font-bold">{guide.bestPeriod}</p></div>{guide.highlights.map((item) => <div key={item.label}><MapPin className="h-6 w-6 text-[#c39960]" /><p className="mt-3 text-xs uppercase tracking-widest text-white/40">{item.label}</p><p className="mt-1 font-bold">{item.value}</p></div>)}</section>

  {guide.itinerary && <section><div className="text-center"><Route className="mx-auto h-9 w-9 text-emerald-700" /><p className="mt-3 text-xs font-bold uppercase tracking-[0.2em] text-[#9a7445]">Sur la route</p><h2 className="mt-3 text-3xl font-bold text-neutral-950 sm:text-4xl">Itinéraire vanlife {guide.name}</h2></div><div className="mx-auto mt-10 max-w-3xl border-l-2 border-emerald-100 pl-6">{guide.itinerary.map((step) => <div key={`${step.days}-${step.place}`} className="relative pb-9 last:pb-0"><span className="absolute -left-[31px] top-1 h-3 w-3 rounded-full bg-emerald-600 ring-4 ring-emerald-50" /><p className="text-xs font-bold uppercase tracking-widest text-[#9a7445]">{step.days}</p><h3 className="mt-1 text-xl font-bold text-neutral-950">{step.place}</h3><p className="mt-2 leading-7 text-neutral-600">{step.text}</p></div>)}</div></section>}

  <section><div className="text-center"><ShieldCheck className="mx-auto h-9 w-9 text-emerald-700" /><p className="mt-3 text-xs font-bold uppercase tracking-[0.2em] text-[#9a7445]">Le réseau Label Vanlife</p><h2 className="mt-3 text-3xl font-bold text-neutral-950 sm:text-4xl">{partners.length ? `${partners.length} ${partners.length > 1 ? "lieux labellisés" : "lieu labellisé"} pour cette destination` : "Les prochaines étapes labellisées de la région"}</h2></div>{partners.length ? <div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{partners.map((lieu) => <Link key={lieu.id} href={`/lieux/${lieu.id}`} className="micro-card group overflow-hidden rounded-2xl border border-neutral-200 bg-white"><div className="relative aspect-[16/10]"><Image src={lieu.photoUrl || "/images/hero-label-vanlife.png"} alt={lieu.nom} fill sizes="(max-width:768px) 100vw,33vw" className="object-cover transition duration-500 group-hover:scale-105" /></div><div className="p-5"><p className="text-xs font-bold uppercase tracking-widest text-[#9a7445]">{lieu.ville}</p><h3 className="mt-1 text-lg font-bold text-neutral-950">{lieu.nom}</h3><p className="mt-2 line-clamp-3 text-sm leading-6 text-neutral-600">{lieu.description}</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-emerald-700">Voir la fiche <ArrowRight className="h-4 w-4" /></span></div></Link>)}</div> : <div className="mx-auto mt-8 max-w-2xl rounded-2xl border border-dashed border-neutral-300 bg-neutral-50 p-8 text-center"><p className="leading-7 text-neutral-600">Aucun établissement de la base actuelle n’est encore rattaché à cette destination. La page sera enrichie dès qu’un lieu de la région rejoindra le réseau.</p><Link href="/explorer" className="mt-5 inline-flex font-bold text-emerald-700">Explorer tous les lieux <ArrowRight className="ml-2 h-4 w-4" /></Link></div>}</section>

  <section className="rounded-3xl bg-gradient-to-br from-emerald-600 to-emerald-800 p-8 text-center text-white sm:p-12"><p className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-200">Préparer le voyage</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Retrouvez les lieux et leurs informations détaillées</h2><p className="mx-auto mt-4 max-w-2xl text-emerald-50/80">Équipements, conditions d’accueil et avantages membres : organisez vos étapes avant le départ.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/explorer"><Button variant="cta" size="lg" className="w-full sm:w-auto">Voir la carte <ArrowRight className="h-4 w-4" /></Button></Link><Link href="/vanlife-regions"><Button variant="secondary" size="lg" className="w-full sm:w-auto">Toutes les régions</Button></Link></div></section></article></main>;
}
